import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export type PlanDay = {
  dayIndex: number;
  dayEn: string;
  dayAr: string;
  date: string;
  platform: string;
  contentType: string;
  topic: string;
  topicAr?: string;
  caption: string;
  captionAr?: string;
  hashtags: string[];
  postingTime: string;
  imagePromptHint?: string;
};

export type ContentPlan = {
  weekTheme: string;
  weekThemeAr: string;
  days: PlanDay[];
  weeklyStrategy?: string;
  expectedEngagement?: string;
};

export type Company = {
  id: string;
  name: string;
  name_ar?: string | null;
  brand_colors?: string[] | null;
};

export async function exportPlanToPDF(
  plan: ContentPlan,
  company: Company,
  outputLanguage: "en" | "ar" = "ar"
): Promise<void> {
  const div = document.createElement("div");
  div.id = "nawaa-pdf-export";
  div.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 1100px;
    padding: 40px;
    background: #0B1A0F;
    color: #D0EBDA;
    font-family: 'Cairo', 'Plus Jakarta Sans', sans-serif;
    font-size: 14px;
    line-height: 1.5;
  `;

  const dayLabel = (d: PlanDay) => (outputLanguage === "ar" ? d.dayAr : d.dayEn);
  const topicLabel = (d: PlanDay) => (outputLanguage === "ar" && d.topicAr ? d.topicAr : d.topic);

  div.innerHTML = `
    <div style="border-bottom: 2px solid #006C35; padding-bottom: 16px; margin-bottom: 24px;">
      <h1 style="font-size: 24px; color: #C9A84C; margin: 0;">نواة | Nawaa AI</h1>
      <p style="margin: 8px 0 0; color: #7B9E86;">${company.name_ar || company.name} — ${plan.weekThemeAr || plan.weekTheme}</p>
      <p style="margin: 4px 0 0; color: #7B9E86; font-size: 12px;">${plan.days?.[0]?.date} – ${plan.days?.[6]?.date}</p>
    </div>
    <div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 12px;">
      ${(plan.days ?? [])
        .map(
          (d) => `
        <div style="border: 1px solid #172E1F; border-radius: 8px; padding: 12px; background: #061009;">
          <div style="font-weight: 600; color: #00A352;">${dayLabel(d)}</div>
          <div style="font-size: 11px; color: #7B9E86;">${d.date} · ${d.platform}</div>
          <div style="margin-top: 8px; font-weight: 600;">${topicLabel(d)}</div>
          <div style="margin-top: 4px; font-size: 11px; color: #7B9E86; max-height: 60px; overflow: hidden;">${(d.captionAr || d.caption || "").slice(0, 80)}…</div>
          <div style="margin-top: 6px;">${(d.hashtags ?? []).slice(0, 3).join(" ")}</div>
        </div>
      `
        )
        .join("")}
    </div>
    <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #172E1F; font-size: 11px; color: #7B9E86;">
      Generated by Nawaa AI — ${new Date().toLocaleDateString()}
    </div>
  `;

  document.body.appendChild(div);

  try {
    const canvas = await html2canvas(div, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#0B1A0F",
      logging: false,
    });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });
    const pdfW = pdf.internal.pageSize.getWidth();
    const pdfH = pdf.internal.pageSize.getHeight();
    const ratio = Math.min(pdfW / canvas.width, pdfH / canvas.height) * 0.95;
    const w = canvas.width * ratio;
    const h = canvas.height * ratio;
    pdf.addImage(imgData, "PNG", (pdfW - w) / 2, (pdfH - h) / 2, w, h);
    const filename = `NawaaAI-${(company.name || "Plan").replace(/\s+/g, "-")}-Week-${plan.days?.[0]?.date ?? "plan"}.pdf`;
    pdf.save(filename);
  } finally {
    document.body.removeChild(div);
  }
}
